name: LGTM Checks
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  codebase:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Use cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run tests
        run: |
          yarn workspace xpra-html5-client lint
          yarn workspace xpra-html5-client-react lint
          yarn workspace xpra-html5-client typecheck
          yarn workspace xpra-html5-client test
  commit:
    name: commitlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v4

