name: Github Pages
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - run: |
          yarn install --frozen-lockfile
          yarn workspaces run build
          yarn workspace xpra-html5-client docs
          mkdir -p public
          cp -r packages/ui/dist public/client
          cp -r packages/xpra/docs public/docs
      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          destination_dir: ts
