name: Github Pages
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn workspaces run build
      - name: Generate docs
        run: yarn workspace xpra-html5-client docs
      - name: Reduce
        run: |
          mkdir -p public
          cp -r packages/ui/dist public/client
          cp -r packages/xpra/docs public/docs
      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          destination_dir: ts
