name: Github Pages
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: |
          npm install -g yarn
          yarn install --frozen-lockfile
      - name: Build
        run: |
          yarn workspace xpra-av build
          yarn workspace xpra-jsmpeg build
          yarn workspace xpra-html5-client build
          yarn workspace xpra-html5-client docs
          yarn workspace xpra-html5-client-react build
          mkdir -p public
          cp -r packages/ui/dist public/client
          cp -r packages/xpra/docs public/docs
      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          destination_dir: ts
