name: npmjs
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
          fetch-depth: 0
          submodules: true
      - name: Use cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build
        run: |
          yarn workspace xpra-av build
          yarn workspace xpra-jsmpeg build
          yarn workspace xpra-broadway build
          yarn workspace xpra-html5-client build
      - name: Publish
        run: yarn workspace xpra-html5-client publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
