name: npmjs
on:
  release:
    types: [created]
jobs:
  build:
    name: Publish on npmjs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'
      - run: |
          yarn install --frozen-lockfile
          yarn workspace xpra-av build
          yarn workspace xpra-jsmpeg build
          yarn workspace xpra-broadway build
          yarn workspace xpra-html5-client build
      - name: Publish
        run: yarn workspace xpra-html5-client publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
