name: npmjs
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: |
          npm install -g yarn
          yarn install --frozen-lockfile
      - name: Build
        run: yarn workspace xpra-html5-client build
      - name: Publish
        run: yarn workspace xpra-html5-client publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
